[[crds]]
apiVersion = 'acid.zalan.do/v1'
url = 'https://raw.githubusercontent.com/zalando/postgres-operator/v1.14.0/manifests/operatorconfiguration.crd.yaml'

[[crds]]
apiVersion = 'acid.zalan.do/v1'
url = 'https://raw.githubusercontent.com/zalando/postgres-operator/v1.14.0/manifests/postgresql.crd.yaml'

[[crds]]
apiVersion = 'acid.zalan.do/v1'
url = 'https://raw.githubusercontent.com/zalando/postgres-operator/v1.14.0/manifests/postgresteam.crd.yaml'

[[crds]]
apiVersion = 'awx.ansible.com/v1beta1'
url = 'https://github.com/ansible/awx-operator/raw/refs/tags/2.19.1/config/crd/bases/awx.ansible.com_awxbackups.yaml'

[[crds]]
apiVersion = 'awx.ansible.com/v1beta1'
url = 'https://github.com/ansible/awx-operator/raw/refs/tags/2.19.1/config/crd/bases/awx.ansible.com_awxmeshingresses.yaml'

[[crds]]
apiVersion = 'awx.ansible.com/v1beta1'
url = 'https://github.com/ansible/awx-operator/raw/refs/tags/2.19.1/config/crd/bases/awx.ansible.com_awxrestores.yaml'

[[crds]]
apiVersion = 'awx.ansible.com/v1beta1'
url = 'https://github.com/ansible/awx-operator/raw/refs/tags/2.19.1/config/crd/bases/awx.ansible.com_awxs.yaml'

[[crds]]
apiVersion = 'cert-manager.io/v1'
url = 'https://github.com/jetstack/cert-manager/releases/download/v1.18.2/cert-manager.crds.yaml'

[[crds]]
apiVersion = 'crd.projectcalico.org/v1'
url = 'https://raw.githubusercontent.com/projectcalico/calico/v3.30.3/manifests/crds.yaml'

[[crds]]
apiVersion = 'networking.istio.io/v1alpha3'
url = 'https://raw.githubusercontent.com/istio/istio/1.12.1/manifests/charts/base/crds/crd-all.gen.yaml'

[[crds]]
apiVersion = 'rabbitmq.com/v1beta1'
url = 'https://github.com/rabbitmq/cluster-operator/releases/download/v2.16.1/cluster-operator.yml'
